FROM centos:centos7
MAINTAINER neonknight <github@neonknight.ch>

RUN yum -y -q install git rsync
RUN yum -y -q install epel-release
RUN yum -y -q install python-nose pyOpenSSL python-requests python-dns python-pygeoip
RUN yum -y -q install rpm-build